baseURL = "https://dea.gl"
title   = "Bryan Deagle"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # RSS only

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT                      = true
enableGitInfo                        = false
enableEmoji                          = true
enableMissingTranslationPlaceholders = false
disableRSS                           = false
disableSitemap                       = false
disable404                           = false
disableHugoGeneratorInject           = false

[permalinks]
  posts = "/posts/:title/"

[author]
  name = "Bryan Deagle"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata used in document's head
  description = "The homepage of Bryan Deagle"
  keywords    = "Bryan Deagle"
  images      = [""]

  homeSubtitle = "Thoughts, How-Tos, and Ramblings"

  # Prefix of link to the git commit detail page. GitInfo must be enabled.  
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Sharing buttons
  # There are a lot of buttons preconfigured. If you want to change them,
  # generate the buttons here: https://sharingbuttons.io
  # and add them into your own `layouts/partials/sharing-buttons.html`
  enableSharingButtons = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .post-content.

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor   = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask          = "#252627"
    msapplication = "#252627"
    theme         = "#252627"

  [params.logo]
    logoText           = "$ cd /home/bryan"
    logoHomeLink       = "/"
    logoCursorDisabled = false
    logoCursorColor    = "#efa00b"
    logoCursorAnimate  = "2s"

  [params.portrait]
    path     = "/img/me.webp"
    alt      = "Portrait"
    maxWidth = "200px"

  # Social icons
  [[params.social]]
    name = "email"
    url  = "mailto:bryan@dea.gl"

  [[params.social]]
    name = "github"
    url  = "https://github.com/bryandeagle"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/bryandeagle"

  [[params.social]]
    name = "hackerrank"
    url  = "https://www.hackerrank.com/bryan51"

  [[params.social]]
    name = "telegram"
    url  = "https://t.me/bryandeagle"

[languages]
  [languages.en]
    subtitle  = ""
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  # [[menu.main]]
  #   identifier = "web"
  #   name       = "Web"
  #   url        = "categories/web/"
  # [[menu.main]]
  #   identifier = "Coding"
  #   name       = "Coding"
  #   url        = "categories/coding/"
  # [[menu.main]]
  #   identifier = "pm"
  #   name       = "Project Mgmt"
  #   url        = "categories/project-management/"